services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\Acme\Plugins\:
        resource: '../../Plugins/*'

    eXpansion\Bundle\Acme\Plugins\TotoPlugin:
        arguments:
            $players: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}

    eXpansion\Bundle\Acme\Plugins\Test:
        arguments:
            $players: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}
            - {name: 'expansion.plugin', data_provider: 'exp.timer'}

    eXpansion\Bundle\Acme\Plugins\Gui\WindowFactory:
            arguments:
                $name:  "test window"
                $sizeX:  180
                $sizeY:  90
            tags:
                - {name: 'expansion.plugin', data_provider: 'expansion.user_group'}

    eXpansion\Bundle\Acme\Plugins\Gui\MemoryWidgetFactory:
            class: 'eXpansion\Bundle\Acme\Plugins\Gui\MemoryWidgetFactory'
            arguments:
                $name:  "memory"
                $posX: 180
                $posY: 90
                $sizeX: null
                $sizeY: null
            tags:
                - {name: 'expansion.plugin', data_provider: 'expansion.user_group'}
