parameters:
    mania_exchange_enumeration.tracksearch:
             0: "Default"
             2: "Latest tracks"
             3: "Recently awarded"
             4: "Best of the Week"
             5: "Best of the Month"
             10: "Supporter tracks"
             21: "Best of the Week MXKarma"
             22: "Best of the Month MXKarma"
             19: "Competitive Tracks of the Week"
             20: "Competitive Tracks of the Month"

    mania_exchange_enumeration.order:
              -1: "Default"
              0: "Track name "
              1: "Author name"
              6: "Activity"
              8: "Awards"
              10: "Comments"
              13: "Difficulty"
              14: "Length"
              25: "Track value"
              27: "Online rating"
    mania_exchange_enumeration.operators:
              -1: "None"
              0: "Equals"
              1: "Greater than"
              2: "Less than"
              3: "Less than or equal"
              4: "Greater than or equal"
    mania_exchange_enumeration.length:
              -1: "All"
              0: "15 secs"
              1: "30 secs"
              2: "45 secs"
              3: "1 min"
             # 4: "1 m 15 s"
              5: "1 m 30 s"
             # 6: "1 m 45 s"
              7: "2 min"
             # 8: "2 m 30 s"
              9: "3 min"
             # 10: "3 m 30 s"
             # 11: "4 min"
             # 12: "4 m 30 s"
              13: "5 min"
              14: "Long"
    mania_exchange_enumeration.map_styles_sm:
              1: "Solo"
              2: "Team"
              3: "Versus"
              4: "Other"
    mania_exchange_enumeration.map_styles_tm:
              -1: "All"
              1: "Race"
              2: "Fullspeed"
              3: "Tech"
              4: "RPG"
              5: "LOL"
              6: "Press Forward"
              7: "Speedtech"
              8: "Multilap"
              9: "Offroad"
              10: "Trial"
    mania_exchange_enumeration.difficulties:
              -1: "All"
              0: "Beginner"
              1: "Intermediate"
              2: "Advanced"
              3: "Expert"

services:
    _defaults:
        autowire: true
        public: true

    expansion.bundle.maps.gui.window.mapslist_factory:
        class: eXpansion\Bundle\Maps\Plugins\Gui\MapsWindowFactory
        arguments:
            $name:  'expansion_maps.gui.window.title'
            $sizeX: 160
            $sizeY: 90
            $posX:  null
            $posY:  null
            $dataCollectionFactory: '@expansion.gui.gridbuilder.datacollection.array'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.user_group'}

    expansion.bundle.maps.gui.window.jukebox_factory:
        class: eXpansion\Bundle\Maps\Plugins\Gui\JukeboxWindowFactory
        arguments:
            $name:  'expansion_maps.gui.window.jbtitle'
            $sizeX: 160
            $sizeY: 90
            $posX:  null
            $posY:  null
            $dataCollectionFactory: '@expansion.gui.gridbuilder.datacollection.array'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.user_group'}

    expansion.bundle.maps.gui.window.mania_exchange_window_factory:
        class: eXpansion\Bundle\Maps\Plugins\Gui\ManiaExchangeWindowFactory
        arguments:
            $name:  'expansion_mx.gui.mxsearch.title'
            $sizeX: 210
            $sizeY: 130
            $posX:  null
            $posY:  null
            $dataCollectionFactory: '@expansion.gui.gridbuilder.datacollection.array'
            $tracksearch: '%mania_exchange_enumeration.tracksearch%'
            $order: '%mania_exchange_enumeration.order%'
            $length: '%mania_exchange_enumeration.length%'
            $mapStylesTm: '%mania_exchange_enumeration.map_styles_tm%'
            $mapStylesSm: '%mania_exchange_enumeration.map_styles_sm%'
            $difficulties: '%mania_exchange_enumeration.difficulties%'
            $operator: '%mania_exchange_enumeration.operators%'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.user_group'}

