services:
    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints:
        class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.players'
                $allPlayers: '@expansion.framework.core.user_groups.all_players'
        tags:
          - {name: 'expansion.plugin', data_provider: 'expansion.local_records.race'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}
          #@todo fix widget dataproviders for laps mode, this works only now with ta...

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints"
                $posX: -120
                $posY: 88
                $sizeX: null
                $sizeY: null

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints Updater"
                $playerGroup : "@expansion.framework.core.user_groups.all_players"
                $variables:
                  - {name: "LocalRecordCheckpoints", type: "Integer[Integer]", default: "Integer[Integer]"}