services:
    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints:
        class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.players'
                $allPlayers: '@expansion.framework.core.user_groups.all_players'
        tags:
          - {name: 'expansion.plugin', data_provider: 'expansion.local_records.race|expansion.local_records.lap'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
            tags:
               - {name: expansion.plugin, data_provider: exp.widget }

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints Updater"
                $playerGroup : "@expansion.framework.core.user_groups.all_players"
                $variables:
                  - {name: "LocalRecordCheckpoints", type: "Integer[Integer]", default: "Integer[Integer]"}
            tags:
                - {name: expansion.plugin, data_provider: exp.timer}
                - {name: expansion.plugin, data_provider: expansion.user_group}
