parameters:

services:
    _defaults:
        autowire: true
        public: true

    expansion.bundle.admin.gui.window.scriptsettings_factory:
        class: eXpansion\Bundle\Admin\Plugins\Gui\ScriptSettingsWindowFactory
        arguments:
            $name:  'Script Settings'
            $sizeX: 240
            $sizeY: 120
            $posX:  null
            $posY:  null
            $dataCollectionFactory: '@expansion.gui.gridbuilder.datacollection.array'

    expansion.bundle.admin.gui.window.serversettings_factory:
        class: eXpansion\Bundle\Admin\Plugins\Gui\ServerSettingsWindowFactory
        arguments:
            $name:  'Server Settings'
            $sizeX: 240
            $sizeY: 120
            $posX:  null
            $posY:  null
