parameters: 
  expansion.core.helper.countries.other_code: OTH
  expansion.core.helper.countries.other_label: Other

  expansion.core.helper.countries.mapping:
    'Afghanistan': 'AFG'
    'Albania': 'ALB'
    'Algeria': 'ALG'
    'Andorra': 'AND'
    'Angola': 'ANG'
    'Argentina': 'ARG'
    'Armenia': 'ARM'
    'Aruba': 'ARU'
    'Australia': 'AUS'
    'Austria': 'AUT'
    'Azerbaijan': 'AZE'
    'Bahamas': 'BAH'
    'Bahrain': 'BRN'
    'Bangladesh': 'BAN'
    'Barbados': 'BAR'
    'Belarus': 'BLR'
    'Belgium': 'BEL'
    'Belize': 'BIZ'
    'Benin': 'BEN'
    'Bermuda': 'BER'
    'Bhutan': 'BHU'
    'Bolivia': 'BOL'
    'Bosnia&Herzegovina': 'BIH'
    'Botswana': 'BOT'
    'Brazil': 'BRA'
    'Brunei': 'BRU'
    'Bulgaria': 'BUL'
    'Burkina Faso': 'BUR'
    'Burundi': 'BDI'
    'Cambodia': 'CAM'
    'Cameroon': 'CAR'
    'Canada': 'CAN'
    'Cape Verde': 'CPV'
    'Central African Republic': 'CAF'
    'Chad': 'CHA'
    'Chile': 'CHI'
    'China': 'CHN'
    'Chinese Taipei': 'TPE'
    'Colombia': 'COL'
    'Congo': 'CGO'
    'Costa Rica': 'CRC'
    'Croatia': 'CRO'
    'Cuba': 'CUB'
    'Cyprus': 'CYP'
    'Czech Republic': 'CZE'
    'Czech republic': 'CZE'
    'DR Congo': 'COD'
    'Denmark': 'DEN'
    'Djibouti': 'DJI'
    'Dominica': 'DMA'
    'Dominican Republic': 'DOM'
    'Ecuador': 'ECU'
    'Egypt': 'EGY'
    'El Salvador': 'ESA'
    'Eritrea': 'ERI'
    'Estonia': 'EST'
    'Ethiopia': 'ETH'
    'Fiji': 'FIJ'
    'Finland': 'FIN'
    'France': 'FRA'
    'Gabon': 'GAB'
    'Gambia': 'GAM'
    'Georgia': 'GEO'
    'Germany': 'DEU'
    'Ghana': 'GHA'
    'Greece': 'GRE'
    'Grenada': 'GRN'
    'Guam': 'GUM'
    'Guatemala': 'GUA'
    'Guinea': 'GUI'
    'Guinea-Bissau': 'GBS'
    'Guyana': 'GUY'
    'Haiti': 'HAI'
    'Honduras': 'HON'
    'Hong Kong': 'HKG'
    'Hungary': 'HUN'
    'Iceland': 'ISL'
    'India': 'IND'
    'Indonesia': 'INA'
    'Iran': 'IRI'
    'Iraq': 'IRQ'
    'Ireland': 'IRL'
    'Israel': 'ISR'
    'Italy': 'ITA'
    'Ivory Coast': 'CIV'
    'Jamaica': 'JAM'
    'Japan': 'JPN'
    'Jordan': 'JOR'
    'Kazakhstan': 'KAZ'
    'Kenya': 'KEN'
    'Kiribati': 'KIR'
    'Korea': 'KOR'
    'Kuwait': 'KUW'
    'Kyrgyzstan': 'KGZ'
    'Laos': 'LAO'
    'Latvia': 'LAT'
    'Lebanon': 'LIB'
    'Lesotho': 'LES'
    'Liberia': 'LBR'
    'Libya': 'LBA'
    'Liechtenstein': 'LIE'
    'Lithuania': 'LTU'
    'Luxembourg': 'LUX'
    'Macedonia': 'MKD'
    'Malawi': 'MAW'
    'Malaysia': 'MAS'
    'Mali': 'MLI'
    'Malta': 'MLT'
    'Mauritania': 'MTN'
    'Mauritius': 'MRI'
    'Mexico': 'MEX'
    'Moldova': 'MDA'
    'Monaco': 'MON'
    'Mongolia': 'MGL'
    'Montenegro': 'MNE'
    'Morocco': 'MAR'
    'Mozambique': 'MOZ'
    'Myanmar': 'MYA'
    'Namibia': 'NAM'
    'Nauru': 'NRU'
    'Nepal': 'NEP'
    'Netherlands': 'NED'
    'New Zealand': 'NZL'
    'Nicaragua': 'NCA'
    'Niger': 'NIG'
    'Nigeria': 'NGR'
    'Norway': 'NOR'
    'Oman': 'OMA'
    'Other Countries': 'OTH'
    'Pakistan': 'PAK'
    'Palau': 'PLW'
    'Palestine': 'PLE'
    'Panama': 'PAN'
    'Paraguay': 'PAR'
    'Peru': 'PER'
    'Philippines': 'PHI'
    'Poland': 'POL'
    'Portugal': 'POR'
    'Puerto Rico': 'PUR'
    'Qatar': 'QAT'
    'Romania': 'ROM'
    'Russia': 'RUS'
    'Rwanda': 'RWA'
    'Samoa': 'SAM'
    'San Marino': 'SMR'
    'Saudi Arabia': 'KSA'
    'Senegal': 'SEN'
    'Serbia': 'SCG'
    'Sierra Leone': 'SLE'
    'Singapore': 'SIN'
    'Slovakia': 'SVK'
    'Slovenia': 'SLO'
    'Somalia': 'SOM'
    'South Africa': 'RSA'
    'Spain': 'ESP'
    'Sri Lanka': 'SRI'
    'Sudan': 'SUD'
    'Suriname': 'SUR'
    'Swaziland': 'SWZ'
    'Sweden': 'SWE'
    'Switzerland': 'SUI'
    'Syria': 'SYR'
    'Taiwan': 'TWN'
    'Tajikistan': 'TJK'
    'Tanzania': 'TAN'
    'Thailand': 'THA'
    'Togo': 'TOG'
    'Tonga': 'TGA'
    'Trinidad and Tobago': 'TRI'
    'Tunisia': 'TUN'
    'Turkey': 'TUR'
    'Turkmenistan': 'TKM'
    'Tuvalu': 'TUV'
    'Uganda': 'UGA'
    'Ukraine': 'UKR'
    'United Arab Emirates': 'UAE'
    'United Kingdom': 'GBR'
    'United States of America': 'USA'
    'Uruguay': 'URU'
    'Uzbekistan': 'UZB'
    'Vanuatu': 'VAN'
    'Venezuela': 'VEN'
    'Vietnam': 'VIE'
    'Yemen': 'YEM'
    'Zambia': 'ZAM'
    'Zimbabwe': 'ZIM'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Core\Helpers\:
        resource: '../../Helpers/*'
        exclude: '../../Helpers/{Data,Structures}'

    eXpansion\Framework\Core\Helpers\Countries:
        class: eXpansion\Framework\Core\Helpers\Countries
        arguments:
            $contriesMapping: '%expansion.core.helper.countries.mapping%'
            $otherCountryCode: '%expansion.core.helper.countries.other_code%'
            $otherCountryLabel: '%expansion.core.helper.countries.other_label%'

    eXpansion\Framework\Core\Helpers\Translations:
        class: eXpansion\Framework\Core\Helpers\Translations
        arguments:
            $supportedLocales: ['fr', 'de', 'fi', 'nl', 'en']
            $colorCodes: '%expansion.config.core_chat_color_codes%'
            $glyphIcons: '%expansion.config.core_chat_glyph_icons%'

    eXpansion\Framework\Core\Helpers\FileSystem:
        class: eXpansion\Framework\Core\Helpers\FileSystem
        arguments:
            $connectionType: "%dedicated_connection_type%"
            $remoteAdapter: '@oneup_flysystem.dedicated_user_data_filesystem'

    expansion.helper.data.array_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ArrayFilter'

    expansion.helper.data.object_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ObjectFilter'

    eXpansion\Framework\Core\Helpers\JobRunner\Factory:
        class: eXpansion\Framework\Core\Helpers\JobRunner\Factory
        tags:
            - {name: expansion.plugin, data_provider: exp.timer}

