services:
    _defaults:
        autowire: true
        public: true

    expansion.framework.core.gui.scripts.menu:
        class: eXpansion\Framework\Core\Model\Gui\ManiaScriptFactory
        arguments:
            $relativePath: 'MenuBundle/Resources/maniascript/menu.txtm'
            $className: eXpansion\Framework\Core\Model\Gui\ManiaScript


    eXpansion\Bundle\Menu\Plugins\Gui\MenuFactory:
        class: eXpansion\Bundle\Menu\Plugins\Gui\MenuFactory
        arguments:
            $name:  'Menu Factory'
            $sizeX: 0
            $sizeY: 0
            $posX:  -150
            $posY:  85

    eXpansion\Bundle\Menu\Plugins\Gui\MenuContentFactory:
        class: eXpansion\Bundle\Menu\Plugins\Gui\MenuContentFactory
        arguments:
              $name:  'Menu Content'
              $sizeX: 0
              $sizeY: 0
              $posX:  null
              $posY:  null
              $maniaScriptFactory: "@expansion.framework.core.gui.scripts.menu"
